[collection-names-case]
  enabled = true
  severity = 'warning'
  case = 'camel'

[collection-names-number]
  enabled = true
  severity = 'warning'
  number = 'plural'

[key-names-case]
  enabled = true
  severity = 'warning'
  case = 'camel'

[keys-that-end-in-at-should-refer-to-dates]
  enabled = true
  severity = 'error'
  allow-stringified-days = true
  stringified-days-regex = '^\\d\\d\\d\\d-[01]\\d-[0123]\\d$'

[keys-that-start-with-is-or-has-should-refer-to-booleans]
  enabled = true
  severity = 'error'

[max-key-count]
  enabled = true
  severity = 'warning'
  maximum-excluding-_id = 10

[no-bad-key-names]
  enabled = true
  severity = 'warning'
  names-considered-bad = ["value", "data", "details", "stuff"]

[no-leading-underscores-in-key-names]
  enabled = true
  severity = 'warning'

[no-null]
  enabled = true
  severity = 'warning'

[no-numbers-saved-as-string]
  enabled = true
  severity = 'error'
  strict-number-check = true

[no-undefined]
  enabled = true
  severity = 'warning'
