[collection-names-number]
  enabled = true
  number = 'plural'

[keys-that-end-in-at-should-refer-to-dates]
  enabled = true
  allow-stringified-days = true
  stringified-days-regex = '^\\d\\d\\d\\d-[01]\\d-[0123]\\d$'

[no-leading-underscores-in-key-names]
  enabled = true

[key-names-case]
  enabled = true
  case = 'camel'

[no-undefined]
  enabled = true

[keys-that-start-with-is-or-has-should-refer-to-booleans]
  enabled = true

[max-key-count]
  enabled = true
  maximum-excluding-_id = 10
